--
-- PostgreSQL database dump
--

-- Dumped from database version 11.20
-- Dumped by pg_dump version 15.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: SyncService; Type: DATABASE; Schema: -; Owner: sync_service
--

CREATE DATABASE "SyncService" WITH TEMPLATE = template0 ENCODING = 'UTF8' LC_COLLATE = 'en_US.utf8' LC_CTYPE = 'en_US.utf8';
ALTER DATABASE "SyncService" OWNER TO sync_service;

CREATE DATABASE "SyncService_Hangfire" WITH OWNER sync_service;

\connect "SyncService" sync_service

SET SCHEMA 'public';

-- The following script was generated by running `dotnet ef migrations script --context SyncServiceDbContextPostgres --idempotent`

CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200522152912_InitialCreate') THEN
    CREATE TABLE "AdminData" (
        "Key" character varying(128) NOT NULL,
        "Value" bytea NOT NULL,
        "Expiry" timestamp without time zone NOT NULL,
        CONSTRAINT "PK_AdminData" PRIMARY KEY ("Key")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200522152912_InitialCreate') THEN
    CREATE TABLE "ProjectSources" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "ProjectId" character varying(64) NOT NULL,
        "SourceId" character varying(128) NOT NULL,
        "SourceName" character varying(128) NULL,
        "PluginName" character varying(128) NULL,
        "PluginVersion" character varying(32) NULL,
        CONSTRAINT "PK_ProjectSources" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200522152912_InitialCreate') THEN
    CREATE TABLE "ProjectSourceManifests" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "CreatedTs" timestamp without time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        "CommittedTs" timestamp without time zone NULL,
        "RegistrationStatus" integer NOT NULL,
        "ProjectSourceId" bigint NOT NULL,
        "SourceManifestId" bigint NULL,
        CONSTRAINT "PK_ProjectSourceManifests" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ProjectSourceManifests_ProjectSources_ProjectSourceId" FOREIGN KEY ("ProjectSourceId") REFERENCES "ProjectSources" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_ProjectSourceManifests_ProjectSourceManifests_SourceManifes~" FOREIGN KEY ("SourceManifestId") REFERENCES "ProjectSourceManifests" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200522152912_InitialCreate') THEN
    CREATE TABLE "ProjectSourceManifestEntries" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "ProjectSourceManifestId" bigint NOT NULL,
        "EntryType" integer NOT NULL,
        "AssetType" integer NOT NULL,
        "PersistentKey" character varying(2080) NOT NULL,
        "ManifestEntryData" bytea NULL,
        CONSTRAINT "PK_ProjectSourceManifestEntries" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ProjectSourceManifestEntries_ProjectSourceManifests_Project~" FOREIGN KEY ("ProjectSourceManifestId") REFERENCES "ProjectSourceManifests" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200522152912_InitialCreate') THEN
    CREATE TABLE "SyncSessions" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "SessionId" uuid NOT NULL,
        "CurrentTransactionNumber" integer NOT NULL,
        "StartedTs" timestamp without time zone NOT NULL,
        "CompletedTs" timestamp without time zone NULL,
        "SessionContextData" bytea NULL,
        "CurrentManifestId" bigint NOT NULL,
        CONSTRAINT "PK_SyncSessions" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_SyncSessions_ProjectSourceManifests_CurrentManifestId" FOREIGN KEY ("CurrentManifestId") REFERENCES "ProjectSourceManifests" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200522152912_InitialCreate') THEN
    CREATE TABLE "SyncSessionAssets" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "SyncSessionId" integer NOT NULL,
        "AssetIdHash" bytea NOT NULL,
        "Hash" bytea NOT NULL,
        "AssetType" integer NOT NULL,
        "ProcessingStatus" integer NOT NULL,
        "TransactionNumber" integer NOT NULL,
        "Priority" integer NOT NULL,
        CONSTRAINT "PK_SyncSessionAssets" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_SyncSessionAssets_SyncSessions_SyncSessionId" FOREIGN KEY ("SyncSessionId") REFERENCES "SyncSessions" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200522152912_InitialCreate') THEN
    CREATE TABLE "SyncSessionRemovedObjectInstances" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "SyncSessionId" integer NOT NULL,
        "TransactionNumber" integer NOT NULL,
        "InstanceId" character varying(2048) NOT NULL,
        CONSTRAINT "PK_SyncSessionRemovedObjectInstances" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_SyncSessionRemovedObjectInstances_SyncSessions_SyncSessionId" FOREIGN KEY ("SyncSessionId") REFERENCES "SyncSessions" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200522152912_InitialCreate') THEN
    CREATE TABLE "SyncSessionTransactions" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "SyncSessionId" integer NOT NULL,
        "TransactionId" uuid NOT NULL,
        "Status" integer NOT NULL,
        "CreatedOn" timestamp without time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        "TransactionNumber" integer NOT NULL,
        "IsCancellationRequested" boolean NOT NULL,
        CONSTRAINT "PK_SyncSessionTransactions" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_SyncSessionTransactions_SyncSessions_SyncSessionId" FOREIGN KEY ("SyncSessionId") REFERENCES "SyncSessions" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200522152912_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_ProjectSourceManifestEntries_ProjectSourceManifestId_Persis~" ON "ProjectSourceManifestEntries" ("ProjectSourceManifestId", "PersistentKey");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200522152912_InitialCreate') THEN
    CREATE INDEX "IX_ProjectSourceManifests_ProjectSourceId" ON "ProjectSourceManifests" ("ProjectSourceId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200522152912_InitialCreate') THEN
    CREATE INDEX "IX_ProjectSourceManifests_RegistrationStatus" ON "ProjectSourceManifests" ("RegistrationStatus");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200522152912_InitialCreate') THEN
    CREATE INDEX "IX_ProjectSourceManifests_SourceManifestId" ON "ProjectSourceManifests" ("SourceManifestId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200522152912_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_ProjectSources_ProjectId_SourceId" ON "ProjectSources" ("ProjectId", "SourceId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200522152912_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_SyncSessionAssets_SyncSessionId_TransactionNumber_AssetType~" ON "SyncSessionAssets" ("SyncSessionId", "TransactionNumber", "AssetType", "AssetIdHash");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200522152912_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_SyncSessionRemovedObjectInstances_SyncSessionId_Transaction~" ON "SyncSessionRemovedObjectInstances" ("SyncSessionId", "TransactionNumber", "InstanceId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200522152912_InitialCreate') THEN
    CREATE INDEX "IX_SyncSessions_CurrentManifestId" ON "SyncSessions" ("CurrentManifestId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200522152912_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_SyncSessions_SessionId" ON "SyncSessions" ("SessionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200522152912_InitialCreate') THEN
    CREATE INDEX "IX_SyncSessionTransactions_SyncSessionId" ON "SyncSessionTransactions" ("SyncSessionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200522152912_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_SyncSessionTransactions_TransactionId" ON "SyncSessionTransactions" ("TransactionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200522152912_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20200522152912_InitialCreate', '6.0.3');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200528180810_AddRuleEngineGroupItems') THEN
    CREATE TABLE "SyncSessionRuleEngineGroupItems" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "SyncSessionId" integer NOT NULL,
        "RuleId" character varying(16) NOT NULL,
        "GroupKey" character varying(4096) NOT NULL,
        "ItemKey" character varying(2080) NOT NULL,
        "ItemType" integer NOT NULL,
        "ItemDataType" character varying(1024) NULL,
        "ItemData" bytea NULL,
        "DependenciesData" bytea NOT NULL,
        "ModifiedByTransactionNumber" integer NOT NULL,
        "IsRemoved" boolean NOT NULL,
        CONSTRAINT "PK_SyncSessionRuleEngineGroupItems" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_SyncSessionRuleEngineGroupItems_SyncSessions_SyncSessionId" FOREIGN KEY ("SyncSessionId") REFERENCES "SyncSessions" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200528180810_AddRuleEngineGroupItems') THEN
    CREATE INDEX "IX_SyncSessionAssets_SyncSessionId_TransactionNumber_Processin~" ON "SyncSessionAssets" ("SyncSessionId", "TransactionNumber", "ProcessingStatus", "Priority");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200528180810_AddRuleEngineGroupItems') THEN
    CREATE UNIQUE INDEX "IX_SyncSessionRuleEngineGroupItems_SyncSessionId_RuleId_GroupK~" ON "SyncSessionRuleEngineGroupItems" ("SyncSessionId", "RuleId", "GroupKey") WHERE "ItemType" = 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200528180810_AddRuleEngineGroupItems') THEN
    CREATE UNIQUE INDEX "IX_SyncSessionRuleEngineGroupItems_SyncSessionId_RuleId_ItemKey" ON "SyncSessionRuleEngineGroupItems" ("SyncSessionId", "RuleId", "ItemKey") WHERE "ItemType" = 1 AND "IsRemoved" = false;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200528180810_AddRuleEngineGroupItems') THEN
    CREATE UNIQUE INDEX "IX_SyncSessionRuleEngineGroupItems_SyncSessionId_RuleId_Group~1" ON "SyncSessionRuleEngineGroupItems" ("SyncSessionId", "RuleId", "GroupKey", "ItemKey") WHERE "ItemType" = 1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200528180810_AddRuleEngineGroupItems') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20200528180810_AddRuleEngineGroupItems', '6.0.3');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200609142603_IdentityColumn') THEN
    ALTER TABLE "SyncSessions" ALTER COLUMN "SessionContextData" SET NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200609142603_IdentityColumn') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20200609142603_IdentityColumn', '6.0.3');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201130175720_SyncSessionIndexesAndNotificationThrottle') THEN
    DROP INDEX "IX_SyncSessionTransactions_SyncSessionId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201130175720_SyncSessionIndexesAndNotificationThrottle') THEN
    DROP INDEX "IX_SyncSessionAssets_SyncSessionId_TransactionNumber_Processin~";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201130175720_SyncSessionIndexesAndNotificationThrottle') THEN
    CREATE TABLE "SyncSessionAssetNotificationThrottle" (
        "InsertTs" timestamp without time zone NOT NULL DEFAULT (date_trunc('second', now())),
        "SyncSessionId" integer NOT NULL,
        CONSTRAINT "PK_SyncSessionAssetNotificationThrottle" PRIMARY KEY ("SyncSessionId", "InsertTs")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201130175720_SyncSessionIndexesAndNotificationThrottle') THEN
    CREATE UNIQUE INDEX "IX_SyncSessionTransactions_SyncSessionId_TransactionNumber" ON "SyncSessionTransactions" ("SyncSessionId", "TransactionNumber");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201130175720_SyncSessionIndexesAndNotificationThrottle') THEN
    CREATE INDEX "IX_SyncSessionAssets_SyncSessionId_TransactionNumber_Processin~" ON "SyncSessionAssets" ("SyncSessionId", "TransactionNumber", "ProcessingStatus");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201130175720_SyncSessionIndexesAndNotificationThrottle') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20201130175720_SyncSessionIndexesAndNotificationThrottle', '6.0.3');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210118185311_TimestampUTC') THEN
    ALTER TABLE "SyncSessionTransactions" ALTER COLUMN "CreatedOn" SET DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210118185311_TimestampUTC') THEN
    ALTER TABLE "ProjectSourceManifests" ALTER COLUMN "CreatedTs" SET DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210118185311_TimestampUTC') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20210118185311_TimestampUTC', '6.0.3');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210331181112_AddingAssetTypeToRemoveRootAssets') THEN
    DROP INDEX "IX_SyncSessionRemovedObjectInstances_SyncSessionId_Transaction~";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210331181112_AddingAssetTypeToRemoveRootAssets') THEN
    ALTER TABLE "SyncSessionRemovedObjectInstances" ADD "AssetType" integer NOT NULL DEFAULT 5;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210331181112_AddingAssetTypeToRemoveRootAssets') THEN
    CREATE UNIQUE INDEX "IX_SyncSessionRemovedObjectInstances_SyncSessionId_Transaction~" ON "SyncSessionRemovedObjectInstances" ("SyncSessionId", "TransactionNumber", "InstanceId", "AssetType");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210331181112_AddingAssetTypeToRemoveRootAssets') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20210331181112_AddingAssetTypeToRemoveRootAssets', '6.0.3');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210510130616_SyncSessionAssetPersistentKey') THEN
    ALTER TABLE "SyncSessionAssets" ADD "PersistentKey" character varying(2080) NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210510130616_SyncSessionAssetPersistentKey') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20210510130616_SyncSessionAssetPersistentKey', '6.0.3');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210520191618_SyncSessionTransactionProgress') THEN
    ALTER TABLE "SyncSessionTransactions" ADD "ProcessedAssetsCount" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210520191618_SyncSessionTransactionProgress') THEN
    ALTER TABLE "SyncSessionTransactions" ADD "TotalAssetsCount" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210520191618_SyncSessionTransactionProgress') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20210520191618_SyncSessionTransactionProgress', '6.0.3');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210526011542_PurgeUnchangedEntriesFlag') THEN
    ALTER TABLE "ProjectSourceManifests" ADD "HasPurgedUnchangedEntries" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210526011542_PurgeUnchangedEntriesFlag') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20210526011542_PurgeUnchangedEntriesFlag', '6.0.3');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210818133456_SyncSessionStatus') THEN
    ALTER TABLE "SyncSessions" ADD "RetryCount" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210818133456_SyncSessionStatus') THEN
    ALTER TABLE "SyncSessions" ADD "Status" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210818133456_SyncSessionStatus') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20210818133456_SyncSessionStatus', '6.0.3');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210819001839_HlodProjectSource') THEN
    ALTER TABLE "ProjectSources" ADD "IsGenerated" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210819001839_HlodProjectSource') THEN
    ALTER TABLE "ProjectSourceManifests" ADD "RootNodeId" text NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210819001839_HlodProjectSource') THEN
    ALTER TABLE "ProjectSourceManifests" ADD "Discriminator" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210819001839_HlodProjectSource') THEN
    CREATE TABLE "ProjectSourceRelatedManifests" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "SourceManifestId" bigint NOT NULL,
        "RelatedManifestId" bigint NOT NULL,
        CONSTRAINT "PK_ProjectSourceRelatedManifests" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ProjectSourceRelatedManifests_ProjectSourceManifests_Relate~" FOREIGN KEY ("RelatedManifestId") REFERENCES "ProjectSourceManifests" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_ProjectSourceRelatedManifests_ProjectSourceManifests_Source~" FOREIGN KEY ("SourceManifestId") REFERENCES "ProjectSourceManifests" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210819001839_HlodProjectSource') THEN
    CREATE INDEX "IX_ProjectSourceRelatedManifests_RelatedManifestId" ON "ProjectSourceRelatedManifests" ("RelatedManifestId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210819001839_HlodProjectSource') THEN
    CREATE UNIQUE INDEX "IX_ProjectSourceRelatedManifests_SourceManifestId_RelatedManif~" ON "ProjectSourceRelatedManifests" ("SourceManifestId", "RelatedManifestId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210819001839_HlodProjectSource') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20210819001839_HlodProjectSource', '6.0.3');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210914162305_SyncSessionUnchangedEntries') THEN
    CREATE TABLE "SyncSessionUnchangedAssets" (
        "SyncSessionId" integer NOT NULL,
        "PersistentKey" text NOT NULL,
        CONSTRAINT "PK_SyncSessionUnchangedAssets" PRIMARY KEY ("SyncSessionId", "PersistentKey"),
        CONSTRAINT "FK_SyncSessionUnchangedAssets_SyncSessions_SyncSessionId" FOREIGN KEY ("SyncSessionId") REFERENCES "SyncSessions" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210914162305_SyncSessionUnchangedEntries') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20210914162305_SyncSessionUnchangedEntries', '6.0.3');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210923165508_HlodConcurrencyToken') THEN
    ALTER TABLE "ProjectSourceManifests" ADD "ConcurrencyToken" integer NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210923165508_HlodConcurrencyToken') THEN
    CREATE UNIQUE INDEX "IX_ProjectSourceManifests_ProjectSourceId_ConcurrencyToken" ON "ProjectSourceManifests" ("ProjectSourceId", "ConcurrencyToken") WHERE "ConcurrencyToken" > 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210923165508_HlodConcurrencyToken') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20210923165508_HlodConcurrencyToken', '6.0.3');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20211021182831_HasSpatializedObjectsFlag') THEN
    ALTER TABLE "ProjectSourceRelatedManifests" ADD "HasSpatializedObjects" boolean NOT NULL DEFAULT TRUE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20211021182831_HasSpatializedObjectsFlag') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20211021182831_HasSpatializedObjectsFlag', '6.0.3');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20211105194552_ProjectSourceManifestEntryAssetTypeIndex') THEN
    CREATE INDEX "IX_ProjectSourceManifestEntries_ProjectSourceManifestId_AssetT~" ON "ProjectSourceManifestEntries" ("ProjectSourceManifestId", "AssetType");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20211105194552_ProjectSourceManifestEntryAssetTypeIndex') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20211105194552_ProjectSourceManifestEntryAssetTypeIndex', '6.0.3');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220121023500_MessageBroker') THEN
    DROP TABLE "SyncSessionAssetNotificationThrottle";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220121023500_MessageBroker') THEN
    DROP TABLE "SyncSessionUnchangedAssets";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220121023500_MessageBroker') THEN
    DROP INDEX "IX_SyncSessionAssets_SyncSessionId_TransactionNumber_AssetType~";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220121023500_MessageBroker') THEN
    ALTER TABLE "SyncSessionTransactions" ADD "PendingAssetsCount" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220121023500_MessageBroker') THEN
    ALTER TABLE "SyncSessionTransactions" ADD "ProcessingPhase" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220121023500_MessageBroker') THEN
    ALTER TABLE "SyncSessionRuleEngineGroupItems" ADD "ProcessingStatus" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220121023500_MessageBroker') THEN
    ALTER TABLE "SyncSessionRemovedObjectInstances" ADD "ProcessingStatus" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220121023500_MessageBroker') THEN
    ALTER TABLE "SyncSessionAssets" ADD "ConcurrencyToken" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220121023500_MessageBroker') THEN
    ALTER TABLE "SyncSessionAssets" ADD "DependencyResolutionPolicy" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220121023500_MessageBroker') THEN
    ALTER TABLE "SyncSessionAssets" ADD "MissingDependency" character varying(2080) NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220121023500_MessageBroker') THEN
    CREATE UNIQUE INDEX "IX_SyncSessionAssets_SyncSessionId_TransactionNumber_Persisten~" ON "SyncSessionAssets" ("SyncSessionId", "TransactionNumber", "PersistentKey");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220121023500_MessageBroker') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20220121023500_MessageBroker', '6.0.3');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220318201033_ProjectSourceManifestSessionState') THEN
    ALTER TABLE "ProjectSourceManifests" ADD "SessionContextData" bytea NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220318201033_ProjectSourceManifestSessionState') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20220318201033_ProjectSourceManifestSessionState', '6.0.3');
    END IF;
END $EF$;
COMMIT;


START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20231121202436_AddSyncServiceIndex') THEN
CREATE INDEX "IX_SyncSessions_StartedTs_Status" ON "SyncSessions" ("StartedTs", "Status");
END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20231121202436_AddSyncServiceIndex') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20231121202436_AddSyncServiceIndex', '6.0.3');
END IF;
END $EF$;
COMMIT;


