apiVersion: v1
kind: Secret
metadata:
  name: project-external-secrets
  namespace: opr-develop
  labels:
    app: project-reflect-common-chart
type: Opaque
stringData:
  REFLECTPROJECT_ConnectionStrings__ProjectServiceDatabase: "Host=opr-postgresql;Database=ProjectService;Username=project_service;Password=reflect"
  REFLECTPROJECT_SyncServer__Cloud__ClientId: "syncid"
  REFLECTPROJECT_SyncServer__Cloud__ClientSecret: "syncsecret"