{{- if .Values.certManager }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: reflect-letsencrypt-issuer
spec:
  acme:
    email: {{ .Values.certManager.issuer.acmeEmail }}
    server: https://acme-v02.api.letsencrypt.org/directory
    preferredChain: {{ .Values.certManager.issuer.preferredChain }}
    privateKeySecretRef:
      name: reflect-letsencrypt-issuer-account-key
    solvers:
    - dns01:
        route53:
          region: {{ .Values.certManager.issuer.awsRegion }}
          hostedZoneID: Z003045025KEQUS78IRZI # Route 53 Hosted Zone ID
          role: {{ .Values.certManager.issuer.awsIAMRole }}
{{- end -}}
