{{- range $key, $value := .Values.certManager.certificates }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $key }}
  namespace: {{ $value.namespace }}
spec:
  secretName: {{ $key }}
  issuerRef:
    name: reflect-letsencrypt-issuer
    kind: ClusterIssuer
  dnsNames:
    {{- toYaml $value.dnsNames | nindent 4 }}
---
{{- end -}}
