apiVersion: apps/v1
kind: Deployment
metadata:
  name: project
  namespace: opr-develop
  labels:
    app.kubernetes.io/instance: opr
    app.kubernetes.io/name: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: opr
      app.kubernetes.io/name: project
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: opr
        app.kubernetes.io/name: project
    spec:
      imagePullSecrets:
        - name: regcred-gcp
      containers:
      - name: project
        image: us-east1-docker.pkg.dev/unity-solutions-tyndall-prd/docker/reflect-project:develop-latest
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: project-external-secrets
        - configMapRef:
            name: project-config
        env:
        - name: ASPNETCORE_URLS
          value: http://+:8090 # Updated to bind to port 8090 instead of 80
        ports:
        - containerPort: 10010
          name: grpc
          protocol: TCP
        - containerPort: 8090 # Updated to match the new internal port
          name: http
          protocol: TCP
        - containerPort: 1234
          name: prom-publisher
          protocol: TCP
        livenessProbe:
          exec:
            command:
            - /bin/grpc_health_probe
            - -addr=:10010
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          exec:
            command:
            - /bin/grpc_health_probe
            - -addr=:10010
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        securityContext:
          capabilities:
            add: ["NET_BIND_SERVICE"] # Add this only if binding to port 80 is required
      - name: envoy
        image: us-east1-docker.pkg.dev/unity-solutions-tyndall-prd/docker/reflect-envoy-k8s:develop-latest
        imagePullPolicy: Always
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 2
      dnsPolicy: ClusterFirst
      hostname: reflect-project
      serviceAccountName: reflect-project-sa
      terminationGracePeriodSeconds: 30
