apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  labels:
  name: mimeo-nginx-vs
  # namespace: nginx
spec:
  gateways:
  - istio-system/mimeo-gateway
  hosts:
  - 'test.kapistiogroup.com'
  http:
  - retries:
      attempts: 3
      perTryTimeout: 2s
    match:
    - uri:
        prefix: /
    route:
    - destination:
        host: test
        port:
          number: 80