
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: sync-api
  namespace: opr-develop
spec:
  gateways:
  - istio-system/mimeo-gateway
  hosts:
  - 'sync-api.kapistiogroup.com'
  http:
  - retries:
      attempts: 3
      perTryTimeout: 2s
    match:
    - uri:
        prefix: /
    route:
    - destination:
        host: sync-api
        port:
          number: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: sync-worker
  namespace: opr-develop
spec:
  gateways:
  - istio-system/mimeo-gateway
  hosts:
  - 'sync-worker.kapistiogroup.com'
  http:
  - retries:
      attempts: 3
      perTryTimeout: 2s
    match:
    - uri:
        prefix: /
    route:
    - destination:
        host: sync-worker
        port:
          number: 80
