apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  labels:
  name: opr-keycloak-http
  namespace: opr-develop
spec:
  gateways:
  - istio-system/mimeo-gateway
  hosts:
  - 'keycloak.kapistiogroup.com'
  http:
  - retries:
      attempts: 3
      perTryTimeout: 2s
    match:
    - uri:
        prefix: /
    route:
    - destination:
        host: opr-keycloak-http
        port:
          number: 80