---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: links
  namespace: opr-develop
spec:
  gateways:
  - istio-system/mimeo-gateway
  hosts:
  - 'links.kapistiogroup.com'
  http:
  - retries:
      attempts: 3
      perTryTimeout: 2s
    match:
    - uri:
        prefix: /
    route:
    - destination:
        host: links
        port:
          number: 80