apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: sample-monitoring
  name: sample-monitoring
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-monitoring
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sample-monitoring
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: sample-monitoring
  name: sample-monitoring
  namespace: monitoring
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: sample-monitoring
status:
  loadBalancer: {}
