apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: macfenty@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - dns01:
        route53:
          region: us-east-1
          hostedZoneID: Z003045025KEQUS78IRZI # Route 53 Hosted Zone ID
          role: arn:aws:iam::440744236785:role/cert-manager-2024122710575978590000000f