--
-- PostgreSQL database dump
--

-- Dumped from database version 11.20
-- Dumped by pg_dump version 15.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

CREATE DATABASE "Annotations" WITH TEMPLATE = template0 ENCODING = 'UTF8' LC_COLLATE = 'en_US.utf8' LC_CTYPE = 'en_US.utf8';

GRANT ALL PRIVILEGES ON DATABASE "Annotations" TO annotations;

ALTER DATABASE "Annotations" OWNER TO annotations;

\connect "Annotations" annotations

SET SCHEMA 'public';

-- The following script was generated by running `dotnet ef migrations script --idempotent`
-- with a few syntax corrections:
--    - TRUNCATE TABLE public."NotificationLog"
--    - ALTER TYPE notification_event_type ADD VALUE IF NOT EXISTS 'blob_added_or_edited';  
--    - ALTER TYPE notification_event_type ADD VALUE IF NOT EXISTS 'blob_removed';
CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
  "MigrationId" character varying(150) NOT NULL,
  "ProductVersion" character varying(32) NOT NULL,
  CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
  );


DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210122160517_AddTopicsAndComments') THEN
CREATE TABLE "Topic" (
                       "Id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                       "ServerId" character varying(64) NOT NULL,
                       "ProjectId" character varying(64) NOT NULL,
                       "SourceId" character varying(512) NOT NULL,
                       "SyncObjectId" character varying(512) NOT NULL,
                       "PositionX" real NOT NULL,
                       "PositionY" real NOT NULL,
                       "PositionZ" real NOT NULL,
                       "Title" text NOT NULL,
                       "CreationAuthor" character varying(64) NOT NULL,
                       "CreationDate" timestamp without time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
                       "ModifiedAuthor" character varying(64) NOT NULL,
                       "ModifiedDate" timestamp without time zone NOT NULL,
                       "Description" text NOT NULL,
                       "Stage" integer NOT NULL,
                       CONSTRAINT "PK_Topic" PRIMARY KEY ("Id")
);
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210122160517_AddTopicsAndComments') THEN
CREATE TABLE "TopicComment" (
                              "Id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                              "TopicId" bigint NOT NULL,
                              "Date" timestamp without time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
                              "Author" character varying(64) NOT NULL,
                              "Comment" text NOT NULL,
                              "ModifiedDate" timestamp without time zone NOT NULL,
                              CONSTRAINT "PK_TopicComment" PRIMARY KEY ("Id"),
                              CONSTRAINT "FK_TopicComment_Topic_TopicId" FOREIGN KEY ("TopicId") REFERENCES "Topic" ("Id") ON DELETE CASCADE
);
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210122160517_AddTopicsAndComments') THEN
CREATE INDEX "IX_Topic_ServerId_ProjectId" ON "Topic" ("ServerId", "ProjectId");
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210122160517_AddTopicsAndComments') THEN
CREATE INDEX "IX_TopicComment_TopicId" ON "TopicComment" ("TopicId");
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210122160517_AddTopicsAndComments') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20210122160517_AddTopicsAndComments', '3.1.18');
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210406185100_AddUserTable') THEN
ALTER TABLE "TopicComment" DROP COLUMN "Author";
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210406185100_AddUserTable') THEN
ALTER TABLE "Topic" DROP COLUMN "CreationAuthor";
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210406185100_AddUserTable') THEN
ALTER TABLE "Topic" DROP COLUMN "ModifiedAuthor";
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210406185100_AddUserTable') THEN
ALTER TABLE "TopicComment" ADD "AuthorUserId" bigint NOT NULL DEFAULT 0;
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210406185100_AddUserTable') THEN
ALTER TABLE "Topic" ADD "CreationUserId" bigint NOT NULL DEFAULT 0;
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210406185100_AddUserTable') THEN
ALTER TABLE "Topic" ADD "ModifiedUserId" bigint NULL;
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210406185100_AddUserTable') THEN
CREATE TABLE "User" (
                      "Id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                      "ReflectUserId" character varying(64) NOT NULL,
                      "FullName" character varying(128) NOT NULL,
                      CONSTRAINT "PK_User" PRIMARY KEY ("Id")
);
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210406185100_AddUserTable') THEN
CREATE INDEX "IX_TopicComment_AuthorUserId" ON "TopicComment" ("AuthorUserId");
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210406185100_AddUserTable') THEN
CREATE INDEX "IX_Topic_CreationUserId" ON "Topic" ("CreationUserId");
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210406185100_AddUserTable') THEN
CREATE INDEX "IX_Topic_ModifiedUserId" ON "Topic" ("ModifiedUserId");
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210406185100_AddUserTable') THEN
CREATE UNIQUE INDEX "IX_User_ReflectUserId" ON "User" ("ReflectUserId");
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210406185100_AddUserTable') THEN
ALTER TABLE "Topic" ADD CONSTRAINT "FK_Topic_User_CreationUserId" FOREIGN KEY ("CreationUserId") REFERENCES "User" ("Id") ON DELETE CASCADE;
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210406185100_AddUserTable') THEN
ALTER TABLE "Topic" ADD CONSTRAINT "FK_Topic_User_ModifiedUserId" FOREIGN KEY ("ModifiedUserId") REFERENCES "User" ("Id") ON DELETE RESTRICT;
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210406185100_AddUserTable') THEN
ALTER TABLE "TopicComment" ADD CONSTRAINT "FK_TopicComment_User_AuthorUserId" FOREIGN KEY ("AuthorUserId") REFERENCES "User" ("Id") ON DELETE CASCADE;
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210406185100_AddUserTable') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20210406185100_AddUserTable', '3.1.18');
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210407145637_AddPositionAndCamera') THEN
ALTER TABLE "Topic" DROP COLUMN "PositionX";
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210407145637_AddPositionAndCamera') THEN
ALTER TABLE "Topic" DROP COLUMN "PositionY";
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210407145637_AddPositionAndCamera') THEN
ALTER TABLE "Topic" DROP COLUMN "PositionZ";
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210407145637_AddPositionAndCamera') THEN
ALTER TABLE "TopicComment" ALTER COLUMN "Comment" TYPE character varying(512);
ALTER TABLE "TopicComment" ALTER COLUMN "Comment" SET NOT NULL;
ALTER TABLE "TopicComment" ALTER COLUMN "Comment" DROP DEFAULT;
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210407145637_AddPositionAndCamera') THEN
ALTER TABLE "Topic" ALTER COLUMN "Title" TYPE character varying(512);
ALTER TABLE "Topic" ALTER COLUMN "Title" SET NOT NULL;
ALTER TABLE "Topic" ALTER COLUMN "Title" DROP DEFAULT;
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210407145637_AddPositionAndCamera') THEN
ALTER TABLE "Topic" ALTER COLUMN "Description" TYPE character varying(512);
ALTER TABLE "Topic" ALTER COLUMN "Description" SET NOT NULL;
ALTER TABLE "Topic" ALTER COLUMN "Description" DROP DEFAULT;
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210407145637_AddPositionAndCamera') THEN
ALTER TABLE "Topic" ADD "CameraPositionX" real NULL;
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210407145637_AddPositionAndCamera') THEN
ALTER TABLE "Topic" ADD "CameraPositionY" real NULL;
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210407145637_AddPositionAndCamera') THEN
ALTER TABLE "Topic" ADD "CameraPositionZ" real NULL;
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210407145637_AddPositionAndCamera') THEN
ALTER TABLE "Topic" ADD "CameraRotationW" real NULL;
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210407145637_AddPositionAndCamera') THEN
ALTER TABLE "Topic" ADD "CameraRotationX" real NULL;
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210407145637_AddPositionAndCamera') THEN
ALTER TABLE "Topic" ADD "CameraRotationY" real NULL;
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210407145637_AddPositionAndCamera') THEN
ALTER TABLE "Topic" ADD "CameraRotationZ" real NULL;
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210407145637_AddPositionAndCamera') THEN
ALTER TABLE "Topic" ADD "LocalPositionX" real NULL;
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210407145637_AddPositionAndCamera') THEN
ALTER TABLE "Topic" ADD "LocalPositionY" real NULL;
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210407145637_AddPositionAndCamera') THEN
ALTER TABLE "Topic" ADD "LocalPositionZ" real NULL;
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210407145637_AddPositionAndCamera') THEN
ALTER TABLE "Topic" ADD "WorldPositionX" real NOT NULL DEFAULT 0;
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210407145637_AddPositionAndCamera') THEN
ALTER TABLE "Topic" ADD "WorldPositionY" real NOT NULL DEFAULT 0;
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210407145637_AddPositionAndCamera') THEN
ALTER TABLE "Topic" ADD "WorldPositionZ" real NOT NULL DEFAULT 0;
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210407145637_AddPositionAndCamera') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20210407145637_AddPositionAndCamera', '3.1.18');
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210413182720_AddRotations') THEN
ALTER TABLE "Topic" ADD "LocalRotationW" real NULL;
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210413182720_AddRotations') THEN
ALTER TABLE "Topic" ADD "LocalRotationX" real NULL;
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210413182720_AddRotations') THEN
ALTER TABLE "Topic" ADD "LocalRotationY" real NULL;
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210413182720_AddRotations') THEN
ALTER TABLE "Topic" ADD "LocalRotationZ" real NULL;
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210413182720_AddRotations') THEN
ALTER TABLE "Topic" ADD "WorldRotationW" real NOT NULL DEFAULT 0;
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210413182720_AddRotations') THEN
ALTER TABLE "Topic" ADD "WorldRotationX" real NOT NULL DEFAULT 0;
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210413182720_AddRotations') THEN
ALTER TABLE "Topic" ADD "WorldRotationY" real NOT NULL DEFAULT 0;
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210413182720_AddRotations') THEN
ALTER TABLE "Topic" ADD "WorldRotationZ" real NOT NULL DEFAULT 0;
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210413182720_AddRotations') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20210413182720_AddRotations', '3.1.18');
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210429125502_AddNotificationLog') THEN
CREATE TYPE notification_event_type AS ENUM ('keep_alive', 'topic_added', 'topic_edited', 'topic_removed', 'comment_added', 'comment_edited', 'comment_removed');
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210429125502_AddNotificationLog') THEN
CREATE TABLE "NotificationLog" (
                                 "Id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                 "ServerId" character varying(64) NOT NULL,
                                 "ProjectId" character varying(64) NOT NULL,
                                 "CreationDate" timestamp without time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
                                 "EventType" notification_event_type NOT NULL,
                                 "RawEventData" text NOT NULL,
                                 CONSTRAINT "PK_NotificationLog" PRIMARY KEY ("Id")
);
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210429125502_AddNotificationLog') THEN
CREATE INDEX "IX_NotificationLog_ServerId_ProjectId" ON "NotificationLog" ("ServerId", "ProjectId");
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210429125502_AddNotificationLog') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20210429125502_AddNotificationLog', '3.1.18');
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210923191953_AddCameraLocalTransform') THEN
ALTER TABLE "Topic" ADD "CameraLocalPositionX" real NULL;
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210923191953_AddCameraLocalTransform') THEN
ALTER TABLE "Topic" ADD "CameraLocalPositionY" real NULL;
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210923191953_AddCameraLocalTransform') THEN
ALTER TABLE "Topic" ADD "CameraLocalPositionZ" real NULL;
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210923191953_AddCameraLocalTransform') THEN
ALTER TABLE "Topic" ADD "CameraLocalRotationW" real NULL;
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210923191953_AddCameraLocalTransform') THEN
ALTER TABLE "Topic" ADD "CameraLocalRotationX" real NULL;
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210923191953_AddCameraLocalTransform') THEN
ALTER TABLE "Topic" ADD "CameraLocalRotationY" real NULL;
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210923191953_AddCameraLocalTransform') THEN
ALTER TABLE "Topic" ADD "CameraLocalRotationZ" real NULL;
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210923191953_AddCameraLocalTransform') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20210923191953_AddCameraLocalTransform', '3.1.18');
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20211117153645_AddReadStatus') THEN
CREATE TABLE "TopicCommentRead" (
                                  "TopicCommentId" bigint NOT NULL,
                                  "UserId" bigint NOT NULL,
                                  "DateRead" timestamp without time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
                                  CONSTRAINT "PK_TopicCommentRead" PRIMARY KEY ("UserId", "TopicCommentId"),
                                  CONSTRAINT "FK_TopicCommentRead_TopicComment_TopicCommentId" FOREIGN KEY ("TopicCommentId") REFERENCES "TopicComment" ("Id") ON DELETE CASCADE,
                                  CONSTRAINT "FK_TopicCommentRead_User_UserId" FOREIGN KEY ("UserId") REFERENCES "User" ("Id") ON DELETE CASCADE
);
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20211117153645_AddReadStatus') THEN
CREATE TABLE "TopicRead" (
                           "TopicId" bigint NOT NULL,
                           "UserId" bigint NOT NULL,
                           "DateRead" timestamp without time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
                           CONSTRAINT "PK_TopicRead" PRIMARY KEY ("UserId", "TopicId"),
                           CONSTRAINT "FK_TopicRead_Topic_TopicId" FOREIGN KEY ("TopicId") REFERENCES "Topic" ("Id") ON DELETE CASCADE,
                           CONSTRAINT "FK_TopicRead_User_UserId" FOREIGN KEY ("UserId") REFERENCES "User" ("Id") ON DELETE CASCADE
);
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20211117153645_AddReadStatus') THEN
CREATE INDEX "IX_TopicCommentRead_TopicCommentId" ON "TopicCommentRead" ("TopicCommentId");
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20211117153645_AddReadStatus') THEN
CREATE INDEX "IX_TopicRead_TopicId" ON "TopicRead" ("TopicId");
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20211117153645_AddReadStatus') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20211117153645_AddReadStatus', '3.1.18');
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20211123181647_AddUserIdToNotifLog') THEN
    TRUNCATE TABLE public."NotificationLog";
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20211123181647_AddUserIdToNotifLog') THEN
ALTER TABLE "NotificationLog" ADD "ReflectUserId" character varying(64) NOT NULL DEFAULT '';
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20211123181647_AddUserIdToNotifLog') THEN
CREATE INDEX "IX_NotificationLog_ReflectUserId" ON "NotificationLog" ("ReflectUserId");
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20211123181647_AddUserIdToNotifLog') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20211123181647_AddUserIdToNotifLog', '3.1.18');
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20211207163349_AddModelColors') THEN
CREATE TYPE coloration_feature AS ENUM ('metadata', 'status_tracking', 'timeline', 'third_party');
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20211207163349_AddModelColors') THEN
CREATE TABLE "ModelColor" (
                            "Id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                            "ServerId" character varying(64) NOT NULL,
                            "ProjectId" character varying(64) NOT NULL,
                            "Feature" coloration_feature NOT NULL,
                            "Field" character varying(256) NOT NULL,
                            "Value" text NOT NULL,
                            "R" integer NOT NULL,
                            "G" integer NOT NULL,
                            "B" integer NOT NULL,
                            "A" integer NOT NULL,
                            "ModifiedDate" timestamp without time zone NOT NULL,
                            CONSTRAINT "PK_ModelColor" PRIMARY KEY ("Id")
);
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20211207163349_AddModelColors') THEN
CREATE TABLE "ModelColorPreset" (
                                  "Id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                  "ServerId" character varying(64) NOT NULL,
                                  "ProjectId" character varying(64) NOT NULL,
                                  "Feature" coloration_feature NOT NULL,
                                  "R" integer NOT NULL,
                                  "G" integer NOT NULL,
                                  "B" integer NOT NULL,
                                  "A" integer NOT NULL,
                                  "Index" integer NOT NULL,
                                  CONSTRAINT "PK_ModelColorPreset" PRIMARY KEY ("Id")
);
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20211207163349_AddModelColors') THEN
CREATE UNIQUE INDEX "IX_ModelColor_ServerId_ProjectId_Feature_Field_Value" ON "ModelColor" ("ServerId", "ProjectId", "Feature", "Field", "Value");
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20211207163349_AddModelColors') THEN
CREATE UNIQUE INDEX "IX_ModelColorPreset_ServerId_ProjectId_Feature_Index" ON "ModelColorPreset" ("ServerId", "ProjectId", "Feature", "Index");
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20211207163349_AddModelColors') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20211207163349_AddModelColors', '3.1.18');
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20211208155522_ColorsAreFloats') THEN
ALTER TABLE "ModelColorPreset" ALTER COLUMN "R" TYPE real;
ALTER TABLE "ModelColorPreset" ALTER COLUMN "R" SET NOT NULL;
ALTER TABLE "ModelColorPreset" ALTER COLUMN "R" DROP DEFAULT;
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20211208155522_ColorsAreFloats') THEN
ALTER TABLE "ModelColorPreset" ALTER COLUMN "G" TYPE real;
ALTER TABLE "ModelColorPreset" ALTER COLUMN "G" SET NOT NULL;
ALTER TABLE "ModelColorPreset" ALTER COLUMN "G" DROP DEFAULT;
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20211208155522_ColorsAreFloats') THEN
ALTER TABLE "ModelColorPreset" ALTER COLUMN "B" TYPE real;
ALTER TABLE "ModelColorPreset" ALTER COLUMN "B" SET NOT NULL;
ALTER TABLE "ModelColorPreset" ALTER COLUMN "B" DROP DEFAULT;
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20211208155522_ColorsAreFloats') THEN
ALTER TABLE "ModelColorPreset" ALTER COLUMN "A" TYPE real;
ALTER TABLE "ModelColorPreset" ALTER COLUMN "A" SET NOT NULL;
ALTER TABLE "ModelColorPreset" ALTER COLUMN "A" DROP DEFAULT;
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20211208155522_ColorsAreFloats') THEN
ALTER TABLE "ModelColor" ALTER COLUMN "R" TYPE real;
ALTER TABLE "ModelColor" ALTER COLUMN "R" SET NOT NULL;
ALTER TABLE "ModelColor" ALTER COLUMN "R" DROP DEFAULT;
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20211208155522_ColorsAreFloats') THEN
ALTER TABLE "ModelColor" ALTER COLUMN "G" TYPE real;
ALTER TABLE "ModelColor" ALTER COLUMN "G" SET NOT NULL;
ALTER TABLE "ModelColor" ALTER COLUMN "G" DROP DEFAULT;
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20211208155522_ColorsAreFloats') THEN
ALTER TABLE "ModelColor" ALTER COLUMN "B" TYPE real;
ALTER TABLE "ModelColor" ALTER COLUMN "B" SET NOT NULL;
ALTER TABLE "ModelColor" ALTER COLUMN "B" DROP DEFAULT;
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20211208155522_ColorsAreFloats') THEN
ALTER TABLE "ModelColor" ALTER COLUMN "A" TYPE real;
ALTER TABLE "ModelColor" ALTER COLUMN "A" SET NOT NULL;
ALTER TABLE "ModelColor" ALTER COLUMN "A" DROP DEFAULT;
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20211208155522_ColorsAreFloats') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20211208155522_ColorsAreFloats', '3.1.18');
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220207141515_UserIdLength') THEN
ALTER TABLE "User" ALTER COLUMN "ReflectUserId" TYPE character varying(256);
ALTER TABLE "User" ALTER COLUMN "ReflectUserId" SET NOT NULL;
ALTER TABLE "User" ALTER COLUMN "ReflectUserId" DROP DEFAULT;
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220207141515_UserIdLength') THEN
ALTER TABLE "NotificationLog" ALTER COLUMN "ReflectUserId" TYPE character varying(256);
ALTER TABLE "NotificationLog" ALTER COLUMN "ReflectUserId" SET NOT NULL;
ALTER TABLE "NotificationLog" ALTER COLUMN "ReflectUserId" DROP DEFAULT;
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220207141515_UserIdLength') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20220207141515_UserIdLength', '3.1.18');
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220208174617_AddIssueManagementKeys') THEN
CREATE TYPE issue_management_connector_type AS ENUM ('reflect', 'procore', 'autodesk');
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220208174617_AddIssueManagementKeys') THEN
ALTER TABLE "TopicComment" ADD "IssueManagementKey" text NOT NULL DEFAULT '';
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220208174617_AddIssueManagementKeys') THEN
ALTER TABLE "Topic" ADD "IssueManagementKey" text NOT NULL DEFAULT '';
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220208174617_AddIssueManagementKeys') THEN
ALTER TABLE "Topic" ADD "IssueType" integer NOT NULL DEFAULT 0;
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220208174617_AddIssueManagementKeys') THEN
CREATE TABLE "IssueManagementConnector" (
                                          "Id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                          "IssueManagementKey" issue_management_connector_type NOT NULL,
                                          "AccessToken" text NOT NULL,
                                          "RefreshToken" text NOT NULL,
                                          "ExpiresAt" timestamp without time zone NOT NULL,
                                          "AuthId" text NULL,
                                          "AuthEmail" text NULL,
                                          "AuthName" text NULL,
                                          "UserId" bigint NOT NULL,
                                          CONSTRAINT "PK_IssueManagementConnector" PRIMARY KEY ("Id"),
                                          CONSTRAINT "FK_IssueManagementConnector_User_UserId" FOREIGN KEY ("UserId") REFERENCES "User" ("Id") ON DELETE CASCADE
);
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220208174617_AddIssueManagementKeys') THEN
CREATE TABLE "ProjectConnection" (
                                   "Id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                   "ServerId" character varying(64) NOT NULL,
                                   "ProjectId" character varying(64) NOT NULL,
                                   "IssueManagementKey" issue_management_connector_type NOT NULL,
                                   "BackendData" text NOT NULL,
                                   CONSTRAINT "PK_ProjectConnection" PRIMARY KEY ("Id")
);
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220208174617_AddIssueManagementKeys') THEN
CREATE UNIQUE INDEX "IX_IssueManagementConnector_UserId_IssueManagementKey" ON "IssueManagementConnector" ("UserId", "IssueManagementKey");
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220208174617_AddIssueManagementKeys') THEN
CREATE UNIQUE INDEX "IX_ProjectConnection_ServerId_ProjectId" ON "ProjectConnection" ("ServerId", "ProjectId");
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220208174617_AddIssueManagementKeys') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20220208174617_AddIssueManagementKeys', '3.1.18');
END IF;
END $$;
 
DO $$
BEGIN
  IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220316201222_Blobs') THEN
-- ALTER TYPE notification_event_type ADD VALUE IF NOT EXISTS 'blob_added_or_edited';

-- This is fixed in Postgres 12
-- https://github.com/prisma/prisma/issues/5290#issuecomment-775140829  
-- using the workaround for now
-- https://stackoverflow.com/questions/53149484/error-alter-type-add-cannot-run-inside-a-transaction-block
  
ALTER TABLE "NotificationLog"
ALTER COLUMN "EventType" TYPE VARCHAR(255);

DROP TYPE IF EXISTS notification_event_type;
CREATE TYPE notification_event_type AS ENUM (
    'keep_alive', 'topic_added', 'topic_edited', 'topic_removed', 'comment_added', 'comment_edited', 'comment_removed',
    'blob_added_or_edited'
);

ALTER TABLE "NotificationLog"
ALTER COLUMN "EventType" TYPE notification_event_type
    USING ("EventType"::notification_event_type);
  
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220316201222_Blobs') THEN
-- ALTER TYPE notification_event_type ADD VALUE IF NOT EXISTS 'blob_removed';
      -- This is fixed in Postgres 12
-- https://github.com/prisma/prisma/issues/5290#issuecomment-775140829  
-- using the workaround for now
-- https://stackoverflow.com/questions/53149484/error-alter-type-add-cannot-run-inside-a-transaction-block

ALTER TABLE "NotificationLog"
ALTER COLUMN "EventType" TYPE VARCHAR(255);

DROP TYPE IF EXISTS notification_event_type;
CREATE TYPE notification_event_type AS ENUM (
    'keep_alive', 'topic_added', 'topic_edited', 'topic_removed', 'comment_added', 'comment_edited', 'comment_removed',
    'blob_added_or_edited',
    'blob_removed'
);

ALTER TABLE "NotificationLog"
ALTER COLUMN "EventType" TYPE notification_event_type
    USING ("EventType"::notification_event_type);
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220316201222_Blobs') THEN
CREATE TABLE "Blob" (
                      "Id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                      "ServerId" character varying(64) NOT NULL,
                      "ProjectId" character varying(64) NOT NULL,
                      "BlobId" character varying(128) NOT NULL,
                      "Data" bytea NOT NULL,
                      CONSTRAINT "PK_Blob" PRIMARY KEY ("Id")
);
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220316201222_Blobs') THEN
CREATE UNIQUE INDEX "IX_Blob_ServerId_ProjectId_BlobId" ON "Blob" ("ServerId", "ProjectId", "BlobId");
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220316201222_Blobs') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20220316201222_Blobs', '3.1.18');
END IF;
END $$;

  
