SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: Matchmaker; Type: DATABASE; Schema: -; Owner: matchmaker_service
--

CREATE DATABASE "Matchmaker" WITH TEMPLATE = template0 ENCODING = 'UTF8' LC_COLLATE = 'en_US.utf8' LC_CTYPE = 'en_US.utf8';
ALTER DATABASE "Matchmaker" OWNER TO matchmaker_service;

\connect "Matchmaker" matchmaker_service

SET SCHEMA 'public';

-- The following script was generated by running `dotnet ef migrations script --idempotent`


CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210314233103_InitialCreate') THEN
    CREATE TYPE allocation_status AS ENUM ('requested', 'pending', 'allocated');
    CREATE TYPE attendee_status AS ENUM ('connecting', 'connected', 'collect');
    CREATE TYPE deployment_status AS ENUM ('initializing', 'available', 'allocated', 'pending_collection', 'needs_collection');
    CREATE TYPE pool_slot_status AS ENUM ('empty', 'reserved', 'ready');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210314233103_InitialCreate') THEN
    CREATE TABLE "Avatars" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "RoomId" bigint NOT NULL,
        "UserId" bigint NOT NULL,
        "DeviceId" bigint NOT NULL,
        "Index" integer NOT NULL,
        CONSTRAINT "PK_Avatars" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210314233103_InitialCreate') THEN
    CREATE TABLE "GameServers" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "Uid" text NOT NULL,
        "IP" text NOT NULL,
        "Port" integer NOT NULL,
        "ProcessUID" text NOT NULL,
        "Registered" timestamp without time zone NOT NULL,
        "Status" deployment_status NOT NULL,
        "Created" timestamp without time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
        "LastKeepAlive" timestamp without time zone NOT NULL,
        "LastInteraction" timestamp without time zone NOT NULL,
        "MarkedPending" timestamp without time zone NOT NULL,
        CONSTRAINT "PK_GameServers" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210314233103_InitialCreate') THEN
    CREATE TABLE "Rooms" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "UID" text NOT NULL,
        "Created" timestamp without time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
        CONSTRAINT "PK_Rooms" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210314233103_InitialCreate') THEN
    CREATE TABLE "UsageQueryResults" (
        "RoomId" bigint NOT NULL,
        "UserCount" bigint NULL,
        "AllocId" bigint NULL,
        "ServerId" bigint NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210314233103_InitialCreate') THEN
    CREATE TABLE "Users" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "ExternalId" text NOT NULL,
        "FullName" text NOT NULL,
        "Created" timestamp without time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
        CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210314233103_InitialCreate') THEN
    CREATE TABLE "PoolSlots" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "Status" pool_slot_status NOT NULL,
        "ServerId" bigint NULL,
        "LastUpdate" timestamp without time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
        "ServerUid" text NULL,
        CONSTRAINT "PK_PoolSlots" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_PoolSlots_GameServers_ServerId" FOREIGN KEY ("ServerId") REFERENCES "GameServers" ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210314233103_InitialCreate') THEN
    CREATE TABLE "Allocations" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "RoomId" bigint NOT NULL,
        "ServerId" bigint NULL,
        "TryCount" integer NOT NULL,
        "RestartCount" integer NOT NULL,
        "Status" allocation_status NOT NULL,
        "LastTry" timestamp without time zone NOT NULL,
        "Created" timestamp without time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
        CONSTRAINT "PK_Allocations" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Allocations_Rooms_RoomId" FOREIGN KEY ("RoomId") REFERENCES "Rooms" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Allocations_GameServers_ServerId" FOREIGN KEY ("ServerId") REFERENCES "GameServers" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210314233103_InitialCreate') THEN
    CREATE TABLE "Attendees" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "RoomId" bigint NOT NULL,
        "UserId" bigint NOT NULL,
        "DeviceId" bigint NOT NULL,
        "Status" attendee_status NOT NULL,
        "Created" timestamp without time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
        "LastKeepAlive" timestamp without time zone NOT NULL,
        "Uid" uuid NOT NULL,
        "ProcessUid" text NOT NULL,
        CONSTRAINT "PK_Attendees" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Attendees_Rooms_RoomId" FOREIGN KEY ("RoomId") REFERENCES "Rooms" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Attendees_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210314233103_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Allocations_RoomId" ON "Allocations" ("RoomId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210314233103_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Allocations_ServerId" ON "Allocations" ("ServerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210314233103_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Attendees_Uid" ON "Attendees" ("Uid");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210314233103_InitialCreate') THEN
    CREATE INDEX "IX_Attendees_UserId" ON "Attendees" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210314233103_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Attendees_RoomId_UserId_DeviceId" ON "Attendees" ("RoomId", "UserId", "DeviceId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210314233103_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Avatars_RoomId_UserId_DeviceId" ON "Avatars" ("RoomId", "UserId", "DeviceId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210314233103_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_GameServers_Uid" ON "GameServers" ("Uid");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210314233103_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_PoolSlots_ServerId" ON "PoolSlots" ("ServerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210314233103_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Rooms_UID" ON "Rooms" ("UID");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210314233103_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Users_ExternalId" ON "Users" ("ExternalId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210314233103_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20210314233103_InitialCreate', '6.0.2');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210323004358_AnonymousUserExpiry') THEN
    ALTER TABLE "Users" ADD "ExpiresOn" timestamp without time zone NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210323004358_AnonymousUserExpiry') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20210323004358_AnonymousUserExpiry', '6.0.2');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220207180352_PresentationStatus') THEN
    CREATE TYPE presentation_role AS ENUM ('none', 'attendee', 'presenter');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220207180352_PresentationStatus') THEN
    ALTER TABLE "Attendees" ADD "AttendeeRole" presentation_role NOT NULL DEFAULT 'none'::presentation_role;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220207180352_PresentationStatus') THEN
    ALTER TABLE "Attendees" ADD "LastPresentationEvent" timestamp without time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220207180352_PresentationStatus') THEN
    CREATE UNIQUE INDEX "IX_Attendees_RoomId_AttendeeRole" ON "Attendees" ("RoomId", "AttendeeRole") WHERE "AttendeeRole" = 'presenter'::presentation_role;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220207180352_PresentationStatus') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20220207180352_PresentationStatus', '6.0.2');
    END IF;
END $EF$;
COMMIT;